root = "."
testdata_dir = "testdata"
tmp_dir = "tmp_air"

[build]
  args_bin = []
  bin = "./tmp_air/main"
  cmd = "go build --tags \"fts5\" -o ./tmp_air/main cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp_air", "vendor", "testdata","pkg/web/frontend"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js","ts","tsx","jsx", "json", "md"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
